FROM node:24-slim AS node_source

# ---
FROM rust:slim AS planner
RUN apt-get update && apt-get install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/*
RUN cargo install cargo-chef
COPY . /app/repo
WORKDIR /app/repo
RUN cargo chef prepare --recipe-path recipe.json

# ---
FROM rust:slim AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    perl \
    build-essential \
    mold \
    clang \
    && rm -rf /var/lib/apt/lists/*

COPY --from=node_source /usr/local/lib/node_modules /usr/local/lib/node_modules
COPY --from=node_source /usr/local/bin/node /usr/local/bin/node
RUN ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm \
    && ln -s /usr/local/lib/node_modules/npm/bin/npx-cli.js /usr/local/bin/npx
RUN npm install -g npm@latest pnpm@11

RUN cargo install cargo-chef

WORKDIR /app/repo

COPY --from=planner /app/repo/recipe.json recipe.json
RUN mkdir -p .cargo && \
    printf '[target."x86_64-unknown-linux-gnu"]\nlinker = "clang"\nrustflags = ["-C", "link-arg=-fuse-ld=mold"]\n' > .cargo/config.toml
RUN cargo chef cook --profile heavy-release --recipe-path recipe.json -p panel-rs -p heavy-supervisor

COPY . /app/repo
RUN cd frontend && pnpm install --frozen-lockfile && pnpm build:ci
RUN cargo build --profile heavy-release -p panel-rs -p heavy-supervisor

RUN cp /app/repo/target/heavy-release/panel-rs /app/panel-rs.stock
RUN cp /app/repo/target/heavy-release/heavy-supervisor /app/heavy-supervisor

RUN ln -s /app/repo/target/heavy-release/panel-rs /usr/local/bin/panel-rs
RUN ln -s /app/repo/target/heavy-release/panel-rs /usr/local/bin/calagopus-panel

ENV OCI_CONTAINER=official-heavy
ENV CARGO_BUILD_PROFILE=balanced
ENV PANEL_BIN_NAME=panel-rs

ENTRYPOINT ["/app/heavy-supervisor"]
