DROP INDEX "admin_activities_user_uuid_idx";
DROP INDEX "admin_activities_event_idx";
DROP INDEX "admin_activities_user_uuid_event_idx";
DROP INDEX "server_activities_user_uuid_idx";
DROP INDEX "server_activities_server_uuid_event_idx";
DROP INDEX "server_activities_user_uuid_event_idx";
DROP INDEX "user_activities_user_uuid_idx";
DROP INDEX "user_activities_user_uuid_event_idx";
CREATE INDEX "admin_activities_created_idx" ON "admin_activities" ("created");
CREATE INDEX "admin_activities_user_uuid_created_idx" ON "admin_activities" ("user_uuid","created");
CREATE INDEX "server_activities_created_idx" ON "server_activities" ("created");
CREATE INDEX "server_activities_user_uuid_created_idx" ON "server_activities" ("user_uuid","created");
CREATE INDEX "server_backups_deleting_idx" ON "server_backups" ("deleting");
CREATE INDEX "user_activities_created_idx" ON "user_activities" ("created");
CREATE INDEX "user_activities_user_uuid_created_idx" ON "user_activities" ("user_uuid","created");
CREATE INDEX "user_api_keys_expires_idx" ON "user_api_keys" ("expires");
CREATE INDEX "user_security_keys_created_idx" ON "user_security_keys" ("created");
CREATE INDEX "user_sessions_key_id_idx" ON "user_sessions" ("key_id");
CREATE INDEX "user_sessions_last_used_idx" ON "user_sessions" ("last_used");